<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>EmbyPlaylistManager</AssemblyName>
    <RootNamespace>EmbyPlaylistManager</RootNamespace>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="ThumbImage.png" />
  </ItemGroup>

  <PropertyGroup>
    <EmbySystemPath>C:\Git\Emby-Server\system</EmbySystemPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MediaBrowser.Common">
      <HintPath>$(EmbySystemPath)\MediaBrowser.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Controller">
      <HintPath>$(EmbySystemPath)\MediaBrowser.Controller.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Model">
      <HintPath>$(EmbySystemPath)\MediaBrowser.Model.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Emby.Web.GenericEdit">
      <HintPath>$(EmbySystemPath)\Emby.Web.GenericEdit.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(CI)' != 'true' AND '$(Configuration)' == 'Debug'">
    <Exec Command="copy $(TargetPath) %AppData%\Emby-Server\programdata\plugins\" />
  </Target>

</Project>
